# Generated by Django 4.1.2 on 2023-06-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualorder',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
