# Generated by Django 4.1.2 on 2023-06-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moona', '0003_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderslist',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
